---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning workspace..."
        rm -rf /workspace/output/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  steps:
    - name: run-tests
      image: python:3.8
      script: |
        pip install nose
        nosetests
